import { GoogleGenerativeAI, GenerativeModel } from '@google/generative-ai';
import { Theme, Style } from './types';

let generativeModel: GenerativeModel | undefined;

function getGenerativeModel(): GenerativeModel {
  if (!generativeModel) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error('GEMINI_API_KEY is not set in environment variables.');
    }
    const genAI = new GoogleGenerativeAI(apiKey);
    const modelName = process.env.GEMINI_MODEL || 'gemini-2.5-flash';
    generativeModel = genAI.getGenerativeModel({ model: modelName });
  }
  return generativeModel;
}

/**
 * Generates a blessing text using the Google Gemini API based on the provided theme and style.
 * The generated text will be between 5 and 15 characters long.
 * @param {Theme} theme - The selected theme.
 * @param {Style} style - The selected style.
 * @returns {Promise<string>} A promise that resolves to the generated blessing text.
 */
export async function generateBlessingText(theme: Theme, style: Style): Promise<string> {
  const model = getGenerativeModel();
  const prompt = `請根據主題「${theme.name}」和風格「${style.name}」，生成一句長度介於5到15個字之間（包含5和15）的繁體中文祝福語。請直接提供祝福語文字，不要包含任何其他說明或引號。`;

  let attempts = 0;
  const maxAttempts = 3;

  while (attempts < maxAttempts) {
    try {
      const result = await model.generateContent(prompt);
      const response = await result.response;
      const blessingText = response.text().trim();

      if (blessingText.length >= 5 && blessingText.length <= 15) {
        return blessingText;
      } else {
        console.warn(`Generated text length is out of bounds: "${blessingText}" (${blessingText.length} chars). Retrying...`);
      }
    } catch (error: any) {
      console.error(`Attempt ${attempts + 1} failed:`, error);
      if (error.message.includes('API_KEY')) {
        throw new Error('GEMINI_API_KEY is not set in environment variables.');
      }
    }
    attempts++;
  }

  console.error('Failed to generate a valid blessing text after multiple attempts.');

  // Fallback to a generic blessing generated by Gemini
  try {
    console.log('Attempting to generate a generic fallback blessing...');
    const fallbackPrompt = '請生成一句長度介於5到15個字之間的通用中文祝福語。請直接提供祝福語文字，不要包含任何其他說明或引號。';
    const result = await model.generateContent(fallbackPrompt);
    const response = await result.response;
    const blessingText = response.text().trim();

    if (blessingText.length >= 5 && blessingText.length <= 15) {
      return blessingText;
    }
  } catch (error) {
    console.error('Failed to generate fallback blessing:', error);
  }

  // Final fallback to a hardcoded default blessing
  return '平安喜樂，萬事如意';
}
